/**
 * Données de démonstration pour le dashboard
 * Basé sur les formations réelles de votre formulaire
 */
export const DEMO_DATA = [
  {
    Horodateur: "01/02/2026 08:12",
    "NOM ET PRÉNOMS": "Fallou Fall",
    "DATE ET LIEU DE NAISSANCE": "07/07/1999 à Pikine",
    "NIVEAU D'ÉTUDES": "Master 2",
    "DOMAINE D'ETUDE": "ISM",
    "NUMERO TELEPHONE": "780181888",
    EMAIL: "fallou@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Marketing",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Après-midi",
    "Adresse e-mail": "fallou@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "01/02/2026 09:30",
    "NOM ET PRÉNOMS": "Aminata Diallo",
    "DATE ET LIEU DE NAISSANCE": "15/03/2001 à Dakar",
    "NIVEAU D'ÉTUDES": "Licence 3",
    "DOMAINE D'ETUDE": "Informatique",
    "NUMERO TELEPHONE": "770234567",
    EMAIL: "aminata@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Commerce international",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Matin",
    "Adresse e-mail": "aminata@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "02/02/2026 10:05",
    "NOM ET PRÉNOMS": "Ibrahima Sow",
    "DATE ET LIEU DE NAISSANCE": "22/11/2000 à Thiès",
    "NIVEAU D'ÉTUDES": "BTS",
    "DOMAINE D'ETUDE": "Gestion",
    "NUMERO TELEPHONE": "763456789",
    EMAIL: "ibra@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Gestion des projets",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Soir",
    "Adresse e-mail": "ibra@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "02/02/2026 11:20",
    "NOM ET PRÉNOMS": "Fatou Ndiaye",
    "DATE ET LIEU DE NAISSANCE": "08/05/1998 à Saint-Louis",
    "NIVEAU D'ÉTUDES": "Master 1",
    "DOMAINE D'ETUDE": "Finance",
    "NUMERO TELEPHONE": "781234567",
    EMAIL: "fatou@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "MBA",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Après-midi",
    "Adresse e-mail": "fatou@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "03/02/2026 08:45",
    "NOM ET PRÉNOMS": "Moussa Gueye",
    "DATE ET LIEU DE NAISSANCE": "30/01/2002 à Ziguinchor",
    "NIVEAU D'ÉTUDES": "Licence 2",
    "DOMAINE D'ETUDE": "Droit",
    "NUMERO TELEPHONE": "775678901",
    EMAIL: "moussa@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "MBI",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Matin",
    "Adresse e-mail": "moussa@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "03/02/2026 14:10",
    "NOM ET PRÉNOMS": "Mariama Ba",
    "DATE ET LIEU DE NAISSANCE": "14/09/1999 à Kaolack",
    "NIVEAU D'ÉTUDES": "Master 2",
    "DOMAINE D'ETUDE": "Communication",
    "NUMERO TELEPHONE": "769012345",
    EMAIL: "mariama@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Analyste financier",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Matin",
    "Adresse e-mail": "mariama@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "04/02/2026 09:00",
    "NOM ET PRÉNOMS": "Ousmane Mbaye",
    "DATE ET LIEU DE NAISSANCE": "05/06/2000 à Rufisque",
    "NIVEAU D'ÉTUDES": "Licence 3",
    "DOMAINE D'ETUDE": "Informatique",
    "NUMERO TELEPHONE": "771234567",
    EMAIL: "ousmane@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Comptabilite",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Soir",
    "Adresse e-mail": "ousmane@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "04/02/2026 10:30",
    "NOM ET PRÉNOMS": "Rokhaya Diop",
    "DATE ET LIEU DE NAISSANCE": "19/12/2001 à Touba",
    "NIVEAU D'ÉTUDES": "BTS",
    "DOMAINE D'ETUDE": "Secrétariat",
    "NUMERO TELEPHONE": "773456789",
    EMAIL: "rokhaya@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Cyber-securite",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Après-midi",
    "Adresse e-mail": "rokhaya@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "05/02/2026 08:20",
    "NOM ET PRÉNOMS": "Cheikh Sarr",
    "DATE ET LIEU DE NAISSANCE": "11/04/1997 à Mbour",
    "NIVEAU D'ÉTUDES": "Master 1",
    "DOMAINE D'ETUDE": "Economie",
    "NUMERO TELEPHONE": "785678901",
    EMAIL: "cheikh@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Entreposage",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Soir",
    "Adresse e-mail": "cheikh@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "05/02/2026 11:00",
    "NOM ET PRÉNOMS": "Ndeye Seck",
    "DATE ET LIEU DE NAISSANCE": "27/08/2003 à Dakar",
    "NIVEAU D'ÉTUDES": "Terminale",
    "DOMAINE D'ETUDE": "Scientifique",
    "NUMERO TELEPHONE": "769876543",
    EMAIL: "ndeye@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Ingénieur financier",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Matin",
    "Adresse e-mail": "ndeye@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "06/02/2026 09:15",
    "NOM ET PRÉNOMS": "Pape Diouf",
    "DATE ET LIEU DE NAISSANCE": "03/02/2000 à Louga",
    "NIVEAU D'ÉTUDES": "Licence 1",
    "DOMAINE D'ETUDE": "Philosophie",
    "NUMERO TELEPHONE": "776543210",
    EMAIL: "pape@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Developpeur web",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Soir",
    "Adresse e-mail": "pape@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "06/02/2026 14:45",
    "NOM ET PRÉNOMS": "Aissatou Camara",
    "DATE ET LIEU DE NAISSANCE": "16/10/1998 à Tambacounda",
    "NIVEAU D'ÉTUDES": "Master 2",
    "DOMAINE D'ETUDE": "Médecine",
    "NUMERO TELEPHONE": "781098765",
    EMAIL: "aissatou@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Transport logistique",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Après-midi",
    "Adresse e-mail": "aissatou@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "07/02/2026 08:30",
    "NOM ET PRÉNOMS": "Modou Thiam",
    "DATE ET LIEU DE NAISSANCE": "21/07/2001 à Kolda",
    "NIVEAU D'ÉTUDES": "BTS",
    "DOMAINE D'ETUDE": "Commerce",
    "NUMERO TELEPHONE": "772109876",
    EMAIL: "modou@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Controle de gestion",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Matin",
    "Adresse e-mail": "modou@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "07/02/2026 10:00",
    "NOM ET PRÉNOMS": "Khadija Lo",
    "DATE ET LIEU DE NAISSANCE": "09/03/2002 à Diourbel",
    "NIVEAU D'ÉTUDES": "Licence 2",
    "DOMAINE D'ETUDE": "Langues",
    "NUMERO TELEPHONE": "764321098",
    EMAIL: "khadija@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Informatique",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Soir",
    "Adresse e-mail": "khadija@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "08/02/2026 09:45",
    "NOM ET PRÉNOMS": "Serigne Fall",
    "DATE ET LIEU DE NAISSANCE": "12/01/1999 à Pikine",
    "NIVEAU D'ÉTUDES": "Licence 3",
    "DOMAINE D'ETUDE": "Mathématiques",
    "NUMERO TELEPHONE": "787654321",
    EMAIL: "serigne@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Ressources humaines",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Matin",
    "Adresse e-mail": "serigne@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "08/02/2026 11:30",
    "NOM ET PRÉNOMS": "Adja Niang",
    "DATE ET LIEU DE NAISSANCE": "25/05/2000 à Fatick",
    "NIVEAU D'ÉTUDES": "Master 1",
    "DOMAINE D'ETUDE": "Biologie",
    "NUMERO TELEPHONE": "778765432",
    EMAIL: "adja@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Ingénieur monétique",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Après-midi",
    "Adresse e-mail": "adja@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "09/02/2026 08:00",
    "NOM ET PRÉNOMS": "Babacar Sy",
    "DATE ET LIEU DE NAISSANCE": "18/09/2001 à Saint-Louis",
    "NIVEAU D'ÉTUDES": "BTS",
    "DOMAINE D'ETUDE": "Génie Civil",
    "NUMERO TELEPHONE": "760123456",
    EMAIL: "babacar@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Ingénieur en certification",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Soir",
    "Adresse e-mail": "babacar@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "09/02/2026 13:20",
    "NOM ET PRÉNOMS": "Awa Diallo",
    "DATE ET LIEU DE NAISSANCE": "04/11/2003 à Dakar",
    "NIVEAU D'ÉTUDES": "Terminale",
    "DOMAINE D'ETUDE": "Littéraire",
    "NUMERO TELEPHONE": "773210987",
    EMAIL: "awa@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Communication digitale",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Matin",
    "Adresse e-mail": "awa@gmail.com",
    OPTION: "Présentiel",
  },
  {
    Horodateur: "10/02/2026 09:10",
    "NOM ET PRÉNOMS": "Ibou Faye",
    "DATE ET LIEU DE NAISSANCE": "30/06/1997 à Kaolack",
    "NIVEAU D'ÉTUDES": "Master 2",
    "DOMAINE D'ETUDE": "Sociologie",
    "NUMERO TELEPHONE": "785432109",
    EMAIL: "ibou@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "Ingenieur genie electronique",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Après-midi",
    "Adresse e-mail": "ibou@gmail.com",
    OPTION: "En ligne",
  },
  {
    Horodateur: "10/02/2026 14:00",
    "NOM ET PRÉNOMS": "Coumba Diagne",
    "DATE ET LIEU DE NAISSANCE": "13/08/2002 à Thiès",
    "NIVEAU D'ÉTUDES": "Licence 1",
    "DOMAINE D'ETUDE": "Architecture",
    "NUMERO TELEPHONE": "766789012",
    EMAIL: "coumba@gmail.com",
    "FORMATION OU FILIÈRE SOLLICITÉE": "ISO ENgineering certification",
    "HEURE DISPONIBLE APRÈS VALIDATION DU": "Soir",
    "Adresse e-mail": "coumba@gmail.com",
    OPTION: "Présentiel",
  },
];
